# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  name: SelfHosted
  demands:
  - agent.name -equals ZISHMANSON

steps:
- checkout: self
  clean: true

- script: dotnet restore
  displayName: "Restore"

- script: dotnet build --configuration Release
  displayName: "Build"

- script: dotnet test --configuration Release --no-build
  displayName: "Test"
